# permissions for end users to edit firewallconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firewallconfiguration-editor-role
rules:
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - firewallconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - firewallconfigurations/status
  verbs:
  - get
