# permissions for end users to view ingressnodefirewallconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressnodefirewallconfig-viewer-role
rules:
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingressnodefirewallconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingressnodefirewallconfigs/status
  verbs:
  - get
