# permissions for end users to edit ingressnodefirewallconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressnodefirewallconfig-editor-role
rules:
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingressnodefirewallconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingressnodefirewallconfigs/status
  verbs:
  - get
