# todo: how to best scaffold this?
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: daemon
  namespace: ingress-node-firewall
rules:
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingressnodefirewallnodestates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingressnodefirewallnodestates/finalizers
  verbs:
  - update
- apiGroups:
  - ingress-nodefw.ingress-nodefw
  resources:
  - ingressnodefirewallnodestates/status
  verbs:
  - get
  - patch
  - update
---
# todo: how to scaffold this best?
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: daemon
  namespace: ingress-node-firewall
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: daemon
subjects:
- kind: ServiceAccount
  name: daemon
  namespace: ingress-node-firewall
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: daemon
  namespace: ingress-node-firewall
