apiVersion: ingress-nodefw.ingress-nodefw/v1alpha1
kind: IngressNodeFirewall
metadata:
  name: ingressnodefirewall-sample
spec:
  interfaces:
  - eth0
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  ingress:
  - fromCIDRs:
       - 172.20.0.0/24
    rules:
    - order: 10
      protocol: icmp
      icmpRule:
        icmpType: 8 #ICMP Echo request
      action: deny
